### ISSUE TITLE
Special State leaves

### ISSUE THREAD

**Issue by ChihChengLiang** [thehubbleproject/RedditHubble#82]
Keep leaf 0 for withdraws and 1 for reddit.

This requires some fixes:

1. contract deploy scripts: we assume 1 to be coordinator's leaf
2. tests: We assume reddit's leaf at index 2

**Comment by vaibhavchellani** [comment]
Would be great if we could use `appendDatablock` from IncrementalTree [here](https://github.com/thehubbleproject/RedditHubble/blob/master/contracts/DepositManager.sol#L88) instead of appendleaf so that the node can sync the pubkey for reddit too, currently it assumed that the first 2 accounts have "0" as pubkey.

**Comment by vaibhavchellani** [comment]
Back with some numbers, for 100,000 users we need to airdrop 10 tokens to each of them, so would be great if the reddit account has 1,000,000 tokens in genesis

**Comment by ChihChengLiang** [comment]
Summarizing the offline discussion with @vaibhavchellani 

We go with the deposit approach for now. Adding Reddit at genesis leaves needs hardcode reddit's pubkey and the genesis amount, and it breaks some tests that needs time to fix. DepositFor Reddit we have more flexibility to decide the pubkey and the amount after contracts are deployed.

We plan to keep 2 coordinator accounts and 2 Reddit accounts.

See #104
